config/routes.rb
Rails.application.routes.draw do
  get 'lookup/index'

  get 'grid/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :results
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/grid_controller.rb
class GridController < ApplicationController
  def index
  end
end

app/controllers/lookup_controller.rb
class LookupController < ApplicationController
  def index
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def show
    @results = Result.all
    render json: @results
  end

  def update
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grid_helper.rb
module GridHelper
end

app/helpers/lookup_helper.rb
module LookupHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/grid/index.html.erb
<h1>Grid#index</h1>
<p>Find me in app/views/grid/index.html.erb</p>

<div id="myFlexGrid" data-url="<%= results_path %>"></div>
<div class="input-group">
  <span class="input-group-addon">
    <i class="glyphicon glyphicon-filter"></i>
  </span>
  <input id="fFilter" type="text" class="form-control" placeholder="Filter by Country..." />
</div>

<button data-behaviour="save_grid_changes">Save</button>

<script type="text/javascript">
  $(document).ready(function(){
    BiorailsGrid.init(wijmo, gridData);
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WijmoTest</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lookup/index.html.erb
<h1>Lookup#index</h1>
<p>Find me in app/views/lookup/index.html.erb</p>

app/views/results/show.html.erb
<!-- Put an html response here -->